### ISSUE TITLE
On Windows, need to specify localhost to socket.bind

### ISSUE THREAD

**Issue by ljones-oxts** [s7711/ncom-web#2]
## Summary of Issue

On Windows, `main.py` fails to run with an `OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted`.

This is not an issue with the code as is, but a limitation of the Windows TCP/IP stack.

## Symptoms

As is, running `py main.py` results in the following error on Windows:

![image](https://github.com/s7711/ncom-web/assets/79583262/a55029bc-0a5b-4840-9bfd-f9830d877d59)

## Fix

On line 60 of `ncomrx_thread.py`, need to specify `localhost`:

`self.sock.bind(('localhost', 3000))`

**Comment by s7711** [comment]
Thanks for highlighting the issue. Turns out that "localhost" is not the right option, instead the socket needs to be opened for non-exclusive use. With OxTS software installed the oxts server is running, and this opens port 3000 (non-exclusively). Because I tried to open the port for exclusive access (the default), Windows generated the error. By setting the port for non-exclusive access, both the oxts server and the python program are able to receive data from the same port. See the changes to ncomrx_thread.py in commit hash e910f78 (updated from c0e4724).
